### ISSUE TITLE
Data availability request - PolarRoute Integration 

### ISSUE THREAD

**Issue by SamuelHall700** [icenet-ai/icenet-project#41]
The PolarRoute project has recently demonstrated intergration with IceNet v1 & IceNet v2 forecasts and would like to continue using IceNet as a data-source in future. 

To facilitate this, a known storage location for IceNet forecasts is required (directory on the SAN, name of forecast file). A deployment of PolarRoute can then be configurated to point at this location to be able to generate meshes/routes using IceNet SIC forecasts.

**Comment by JimCircadian** [comment]
Hi @SamuelHall700 

The location is here: `/data/twins/wip/common/icenet/`

I've dropped a recent forecast in this file for you: `north_daily_forecast.2023-02-19.nc`. 

Any new forecasts will be named like this, with the forecast initialisation date in the filename. These are produced ad-hoc however, so you will need to request them. We can produce northern and southern hemisphere.

However, the initialisation date is dependent on the availability of publicly available reanalysis data. We can't use other available data streams for more recent forecasts for various reasons, so please bear that in mind. 😉 

Two very important things:

* **These are development forecasts from development models, please do not treat them otherwise**
* *This might not be the permanent location for you to acquire files from*

**Comment by JimCircadian** [comment]
@SamuelHall700 I've dropped a forecast for both hemispheres in the folder for you: 

```
/data/twins/wip/common/icenet/north_daily_forecast.2023-02-13.nc
/data/twins/wip/common/icenet/south_daily_forecast.2023-02-13.nc
```

Going to close this issue but let me know if you need more forecasts producing.
